services:
  web:
    build: ./
    command: "poetry run -- fastapi run src/main.py --host 0.0.0.0"
    ports:
      - 80:8000
    working_dir: /code
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis
    restart: always
