services:
  #  web:
  #    build: ./
  #    command: "poetry run -- fastapi dev src/main.py --host 0.0.0.0 --reload"
  #    ports:
  #      - 8000:8000
  #    working_dir: /code
  #    volumes:
  #      - .:/code
  #    depends_on:
  #      - db
  #      - redis
  #      - postgres
  #    env_file:
  #      - .env

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: kinnema
      POSTGRES_DB: kinnema
      POSTGRES_PASSWORD: kinnema
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
