services:
  web:
    build: ./
    command: "poetry run -- fastapi dev src/main.py --host 0.0.0.0 --reload"
    ports:
      - 8000:8000
    working_dir: /code
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
