services:
  web:
    build: ./
    command: "poetry run alembic upgrade head && poetry run -- uvicorn src.main:app  --host 0.0.0.0"
    ports:
      - 8123:8000
    working_dir: /code
    volumes:
      - .:/code
    depends_on:
      - redis
      - postgres
    env_file:
      - .env

  redis:
    image: redis
    restart: always

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: kinnema
      POSTGRES_DB: kinnema
      POSTGRES_PASSWORD: kinnema
    ports:
      - 5432:5432
