services:
  database:
    image: postgres
    ports:
      - 5432
    environment:
      - POSTGRES_USER=kinnema
      - POSTGRES_PASSWORD=kinnema
      - POSTGRES_DB=kinnema
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
