"""add tmdb_id 

Revision ID: 0d4c1ee4b97c
Revises: 53cd43dc93d9
Create Date: 2024-06-18 15:35:58.218703

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0d4c1ee4b97c'
down_revision = '53cd43dc93d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lastwatched', sa.Column('tmdb_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lastwatched', 'tmdb_id')
    # ### end Alembic commands ###