"""network

Revision ID: d43492657cbc
Revises: 9f899fdf2569
Create Date: 2024-06-18 15:57:22.189561

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd43492657cbc'
down_revision = '9f899fdf2569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lastwatched', sa.Column('network', sa.Integer(), nullable=True))
    op.drop_column('lastwatched', 'is_turkish_provider')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lastwatched', sa.Column('is_turkish_provider', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('lastwatched', 'network')
    # ### end Alembic commands ###